baseurl         = "https://nudges.netlify.com/"
theme           = "duck-hugo"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 12
#SectionPagesMenu = "main"
canonifyurls    = true
enableEmoji     = true
hasCJKLanguage  = true

[params]
  title       = "Nudges"
  subtitle    = ""
  #copyright   = "Â© 2018"
  copyright   = ""

  cover       = "/img/blog-cover.jpg"
  description = "To feel the life"
  metaDescription = ""
  googleAnalytics = "UA-161620484-1"
  customCSS = []
  RSSLink = ""

  #dateformat = "Jan 2, 2006"

  twitterName = ""
  fbName = ""
  githubName = "fuphy"
  linkedinName = "jie-fu-275a2a5b"
  mediumName = ""
  igName = "phyllis_jf"

  logo = ""
  orgName = ""
  orgWebsite = ""
  orgDescription = "Here is a description placeholder for your org"

  showSupport = false

  author = "Jie Fu"
  authorAvatar = "/img/profile.jpg"
  authorLocation = "Munich, DE"
  authorWebsite = "/categories/post/"
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[permalinks]
  post = "/:section/:title"
  test_folder = "/:section/:title"
  travel = "/:section/:title"
  
  #post = "/post/:slug/"

  
[[menu.main]]
  name = "Home"
  url = "/post/"
  weight = 200

[[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 150

[[menu.main]]
  name = "recipe"
  url = "/categories/recipe/"
  weight = 130

[[menu.main]]
  name = "travel"
  url = "/categories/travel/"
  weight = 100

[[menu.main]]
  name = "thoughts"
  url = "/categories/thoughts/"
  weight = 99

