baseurl         = "/"
theme           = "hugo-casper-two-master"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 12
#SectionPagesMenu = "main"
canonifyurls    = true
enableEmoji     = true
hasCJKLanguage  = true

[params]
  title       = "Nudge"
  subtitle    = "Bilibili"
  copyright   = "Â© 2018"

  cover       = "img/blog-cover.jpg"
  description = "To feel the life"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = "fuphy"
  linkedinName = "jie-fu-275a2a5b"
  mediumName = ""
  igName = "phyllis_jf"

  logo = ""
  orgName = "Jie Fu"
  orgWebsite = ""
  orgDescription = "Here is a description placeholder for your org"

  showSupport = false

  author = "Jie Fu"
  authorAvatar = "/img/profile.jpg"
  authorLocation = "Munich, DE"
  authorWebsite = "/categories/post/"
  authorDescription = "An explorer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = true

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/post/"
  weight = 200

[[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 150

[[menu.main]]
  name = "travel"
  url = "/categories/travel/"
  weight = 100

[[menu.main]]
  name = "thoughts"
  url = "/categories/thoughts/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://www.ankuroh.com/"
  weight = 95